name: DpTradeSankazei
version: '${version}'
main: dptradesankazei.dptradesankazei.DpTradeSankazei
api-version: 1.16
authors: [ Deponn ]
description: We can buy sankazei with this Plugin. It needs DpMarket.

commands: #自作プラグインのコマンドを宣言
  DpEnableTrader:
    description: プラグインを有効にする
    usage: /DpEnableTrader
    permission: tr
  DpDisableTrader:
    description: プラグインを無効にする
    usage: /DpEnableTrader
    permission: tr
  DpInitialize:
    description: 初期化
    usage: /DpInitialize
    permission: tr
  DpRegister:
    description: 変えるプレイヤーを登録する。
    usage: /DpRegister
    permission: tr
  DpSetPrise:
    description: 値段を決定する。
    usage: /  DpSetPrise
    permission: tr
  Buy:
    description: 参加勢を買う
    usage: /  Buy
    permission: tr2


permissions:
  tr:
    description: op only
    default: op
  tr2:
    description: everyone
    default: true